### ISSUE TITLE
origin-helper script does not read FC24 Denuvo ticket Ticket but reading  FIFA 22 Denuvo ticket

### ISSUE THREAD

**Issue by YGV008** [anadius/ea-get-token#3]
thank you for your great effort and i appreciate your work and need your help if it does not bother you
origin-helper script (2.1.12) does not read FC24 Denuvo ticket Ticket but reading  FIFA 22 Denuvo ticket
WHEN I PUT FC24 Denuvo ticket IT KEEPS GETTING ERROR "Error: Unknown type - text/xml" but WHEN I PUT FIFA 22 Denuvo ticket IT Works fine , any tips for solving this issue
thanks in advance
![1](https://github.com/anadius/ea-get-token/assets/164502002/f2a1d7ad-92ee-4300-9fd3-2903473db173)

**Comment by anadius** [comment]
Another fucking idiot. What does it have to do with `get token` program? That's right, nothing.
